#!/usr/bin/env python3
"""
Oral History Workflow - Flet App (Whisper Branch)
A GUI application to streamline the oral history transcription workflow:
1. (Optional) Convert WAV files to MP3
2. Select an MP3 file
3. AUTOMATED TRANSCRIPTION with OpenAI Whisper (NEW!)
4. OR: Manual MS Word Online transcription (legacy)
5. Convert DOCX to CSV and PDF using parse_transcript.py
6. Auto-update PROGRESS_STATUS.md
"""

import flet as ft
import os
import sys
import subprocess
import shutil
import re
from pathlib import Path
from datetime import datetime
from collections import defaultdict

# Import Whisper transcription module
try:
    import transcribe_whisper
    WHISPER_AVAILABLE = True
except ImportError:
    WHISPER_AVAILABLE = False
    transcribe_whisper = None



def scan_reunion_directory():
    """Scan Reunion-2025-Oral-Histories directory and return interview status."""
    reunion_dir = Path("Reunion-2025-Oral-Histories")
    
    if not reunion_dir.exists():
        return None, "Reunion-2025-Oral-Histories directory not found"
    
    # Dictionary to hold interview data
    interviews = defaultdict(lambda: {
        'wav': None, 'mp3': None, 'docx': None, 
        'csv': None, 'pdf': None, 'location': 'root'
    })
    
    # Scan all subdirectories
    for file_path in reunion_dir.rglob('*'):
        if not file_path.is_file():
            continue
            
        # Get the base name without extension
        stem = file_path.stem
        suffix = file_path.suffix.lower()
        
        # Determine location
        if 'backup' in str(file_path):
            location = 'backup'
        elif 'OBJS' in str(file_path):
            location = 'OBJS'
        elif 'from-MacWhisper' in str(file_path):
            location = 'from-MacWhisper'
        else:
            location = 'root'
        
        # Track files by type
        if suffix in ['.wav']:
            interviews[stem]['wav'] = file_path
            interviews[stem]['location'] = location
        elif suffix in ['.mp3']:
            interviews[stem]['mp3'] = file_path
            if not interviews[stem]['wav']:
                interviews[stem]['location'] = location
        elif suffix in ['.docx']:
            interviews[stem]['docx'] = file_path
            if not interviews[stem]['wav'] and not interviews[stem]['mp3']:
                interviews[stem]['location'] = location
        elif suffix in ['.csv'] and not stem.startswith('generated_metadata'):
            interviews[stem]['csv'] = file_path
        elif suffix in ['.pdf']:
            interviews[stem]['pdf'] = file_path
    
    return dict(interviews), None


def update_progress_status():
    """Update PROGRESS_STATUS.md file with current interview status."""
    interviews, error = scan_reunion_directory()
    
    if error:
        return False, error
    
    # Calculate statistics
    complete_count = 0
    in_progress_count = 0
    pending_count = 0
    
    complete_interviews = []
    in_progress_interviews = []
    pending_interviews = []
    
    for name, files in sorted(interviews.items()):
        has_wav = files['wav'] is not None
        has_mp3 = files['mp3'] is not None
        has_docx = files['docx'] is not None
        has_csv = files['csv'] is not None
        has_pdf = files['pdf'] is not None
        
        # Determine status
        if has_wav and has_mp3 and has_docx and has_csv and has_pdf:
            complete_count += 1
            complete_interviews.append((name, files))
        elif has_docx or has_csv or has_pdf or has_mp3:
            in_progress_count += 1
            in_progress_interviews.append((name, files))
        else:
            pending_count += 1
            pending_interviews.append((name, files))
    
    total = len(interviews)
    mp3_count = sum(1 for f in interviews.values() if f['mp3'])
    docx_count = sum(1 for f in interviews.values() if f['docx'])
    csv_count = sum(1 for f in interviews.values() if f['csv'])
    pdf_count = sum(1 for f in interviews.values() if f['pdf'])
    
    # Generate PROGRESS_STATUS.md content
    content = f"""# Reunion 2025 Oral Histories - Progress Status

**Last Updated:** {datetime.now().strftime('%B %d, %Y at %I:%M %p')}  
**Auto-generated by Oral History Workflow App**

## Overview

This document tracks the processing status of all oral history interviews from the Reunion 2025 collection. Each interview progresses through the following workflow stages:

1. **Audio (WAV)** - Original recording
2. **Audio (MP3)** - Compressed format (REQUIRED for completion)
3. **Transcript (DOCX)** - MS Word Online transcription
4. **CSV** - Structured data export
5. **PDF** - Human-readable format

## Progress Legend

- ✅ **Complete** - All 5 stages finished (WAV, MP3, DOCX, CSV, PDF)
- 🟡 **In Progress** - Some stages completed
- ⏳ **Pending** - Only audio file exists
- 📁 **Archived** - Files in backup directory

---

## Summary Statistics

| Status | Count | Percentage |
|--------|-------|------------|
| ✅ Complete (All stages) | {complete_count} | {complete_count/total*100 if total > 0 else 0:.0f}% |
| 🟡 In Progress (Some stages) | {in_progress_count} | {in_progress_count/total*100 if total > 0 else 0:.0f}% |
| ⏳ Pending (Audio only) | {pending_count} | {pending_count/total*100 if total > 0 else 0:.0f}% |
| **TOTAL INTERVIEWS** | **{total}** | **100%** |

### Processing Stages Complete

| Stage | Count | Percentage |
|-------|-------|------------|
| Audio Files (WAV) | {total}/{total} | 100% |
| MP3 Files | {mp3_count}/{total} | {mp3_count/total*100 if total > 0 else 0:.0f}% |
| DOCX Transcripts | {docx_count}/{total} | {docx_count/total*100 if total > 0 else 0:.0f}% |
| CSV Exports | {csv_count}/{total} | {csv_count/total*100 if total > 0 else 0:.0f}% |
| PDF Exports | {pdf_count}/{total} | {pdf_count/total*100 if total > 0 else 0:.0f}% |

---

## Interviews Status

### ✅ Complete ({complete_count} interviews)

"""
    
    # Add complete interviews
    for idx, (name, files) in enumerate(complete_interviews, 1):
        content += f"""#### {idx}. {name}
**Progress:** 100% ✅ COMPLETE
- ✅ WAV: `{files['wav'].name if files['wav'] else 'N/A'}`
- ✅ MP3: `{files['mp3'].name if files['mp3'] else 'N/A'}`
- ✅ DOCX: `{files['docx'].name if files['docx'] else 'N/A'}` (in {files['location']})
- ✅ CSV: `{files['csv'].name if files['csv'] else 'N/A'}`
- ✅ PDF: `{files['pdf'].name if files['pdf'] else 'N/A'}`

"""
    
    content += f"""---

### 🟡 In Progress ({in_progress_count} interviews)

"""
    
    # Add in-progress interviews
    for idx, (name, files) in enumerate(in_progress_interviews, complete_count + 1):
        has_mp3 = files['mp3'] is not None
        has_docx = files['docx'] is not None
        has_csv = files['csv'] is not None
        has_pdf = files['pdf'] is not None
        
        # Calculate progress
        stages_complete = sum([has_mp3, has_docx, has_csv, has_pdf])
        progress = int((stages_complete / 4) * 100)
        
        # Determine what's missing
        missing = []
        if not has_mp3:
            missing.append("MP3")
        if not has_csv:
            missing.append("CSV")
        if not has_pdf:
            missing.append("PDF")
        
        missing_str = ", ".join(missing) if missing else "None"
        
        content += f"""#### {idx}. {name}
**Progress:** {progress}% 🟡 PARTIAL{' - MISSING ' + missing_str if missing else ''}
- ✅ WAV: `{files['wav'].name if files['wav'] else 'N/A'}`
- {'❌ MP3: **MISSING** - **REQUIRED**' if not has_mp3 else f"✅ MP3: `{files['mp3'].name}`"}
- {'❌ DOCX: **MISSING**' if not has_docx else f"✅ DOCX: `{files['docx'].name}` (in {files['location']})"}
- {'❌ CSV: **MISSING**' if not has_csv else f"✅ CSV: `{files['csv'].name}`"}
- {'❌ PDF: **MISSING**' if not has_pdf else f"✅ PDF: `{files['pdf'].name}`"}

**Next Step:** {
    "Convert WAV to MP3 using app" if not has_mp3 
    else "Convert DOCX to CSV & PDF using app" if has_docx and (not has_csv or not has_pdf)
    else "Create transcript in MS Word Online"
}

"""
    
    content += f"""---

### ⏳ Pending Transcription ({pending_count} interviews)

"""
    
    # Add pending interviews
    for idx, (name, files) in enumerate(pending_interviews, complete_count + in_progress_count + 1):
        has_mp3 = files['mp3'] is not None
        content += f"""#### {idx}. {name}
**Progress:** {'40%' if has_mp3 else '20%'} ⏳ AUDIO ONLY
- ✅ WAV: `{files['wav'].name if files['wav'] else 'N/A'}`
- {'✅ MP3: `' + files['mp3'].name + '`' if has_mp3 else '❌ MP3: **MISSING**'}
- ❌ DOCX: **MISSING** - Needs transcription
- ❌ CSV: **MISSING**
- ❌ PDF: **MISSING**

**Next Step:** {'Upload MP3 to MS Word Online' if has_mp3 else 'Convert WAV to MP3, then upload to MS Word Online'}

"""
    
    content += """---

## Priority Action Items

### HIGH PRIORITY: Missing MP3 Files
"""
    
    # Find interviews missing MP3s
    missing_mp3 = [(name, files) for name, files in sorted(interviews.items()) 
                   if files['wav'] and not files['mp3']]
    
    if missing_mp3:
        content += f"{len(missing_mp3)} interviews need MP3 files:\n\n"
        for name, files in missing_mp3:
            wav_size = files['wav'].stat().st_size / (1024**3) if files['wav'] else 0
            content += f"- **{name}.WAV** ({wav_size:.1f} GB) → Convert to MP3 using app\n"
        content += "\n**Tool:** Use the app's WAV converter\n\n"
    else:
        content += "✅ All interviews have MP3 files!\n\n"
    
    content += """### Quick Wins: Convert DOCX to CSV/PDF
"""
    
    # Find interviews with DOCX but missing CSV/PDF
    quick_wins = [(name, files) for name, files in sorted(interviews.items())
                  if files['docx'] and (not files['csv'] or not files['pdf'])]
    
    if quick_wins:
        content += f"{len(quick_wins)} interviews ready for CSV/PDF conversion:\n\n"
        for name, files in quick_wins:
            content += f"- **{name}** → Convert DOCX to CSV & PDF\n"
        content += f"\n**Estimated Time:** ~{len(quick_wins) * 3} minutes\n\n"
    else:
        content += "✅ All transcripts have been converted!\n\n"
    
    content += """---

## Notes

- **Auto-Generated:** This document is automatically updated by the Oral History Workflow app
- **MP3 Files Are Required:** All interviews must have MP3 files to be considered complete
- **WAV Conversion:** Use the app's WAV converter to create MP3s from large WAV files  
- **Refresh Status:** Click "Refresh Status" button in the app to update this document

---

## Workflow Reminder

For each interview:

1. **(If needed) Convert WAV to MP3** → Use app's WAV converter - **REQUIRED**
2. **Upload audio (MP3)** to MS Word Online → Use Transcribe feature
3. **Edit transcript** in Word → Fix speaker names, review text
4. **Save as DOCX** → Use same name as audio file, save in same folder
5. **Run conversion** → Open app, click "Convert DOCX to CSV & PDF"
6. **Refresh Status** → Click "Refresh Status" in app to update this document

**Note:** All stages including MP3 creation must be completed for an interview to be marked as "Complete"

---

**For questions or issues, refer to the main [README.md](README.md) file.**
"""
    
    # Write the file
    try:
        with open('PROGRESS_STATUS.md', 'w', encoding='utf-8') as f:
            f.write(content)
        return True, f"Updated! Found {total} interviews: {complete_count} complete, {in_progress_count} in progress, {pending_count} pending"
    except Exception as e:
        return False, f"Error writing file: {str(e)}"


def main(page: ft.Page):
    page.title = "Oral History Workflow"
    page.padding = 20
    page.window.width = 900
    page.window.height = 700
    
    # State variables
    selected_mp3_path = None
    selected_wav_path = None
    
    # UI Components
    status_text = ft.Text(
        "Ready to begin",
        color=ft.Colors.BLUE_400,
        size=14,
        italic=True
    )
    
    result_text = ft.Text(
        "Select a WAV file to convert, or an MP3 file to begin transcription",
        size=14,
        selectable=True
    )
    
    wav_result_text = ft.Text(
        "",
        size=14,
        selectable=True,
        visible=False
    )
    
    instructions_container = ft.Container(
        visible=False,
        padding=15,
        bgcolor=ft.Colors.BLUE_50,
        border=ft.Border.all(2, ft.Colors.BLUE_300),
        border_radius=8
    )
    
    convert_button = ft.Container(visible=False)
    wav_convert_button = ft.Container(visible=False)
    
    # Whisper transcription UI components
    whisper_model_dropdown = ft.Dropdown(
        label="Whisper Model",
        width=300,
        options=[
            ft.dropdown.Option("tiny", "Tiny (~1GB RAM, fastest, least accurate)"),
            ft.dropdown.Option("base", "Base (~1GB RAM, fast)"),
            ft.dropdown.Option("small", "Small (~2GB RAM, balanced) - RECOMMENDED"),
            ft.dropdown.Option("medium", "Medium (~5GB RAM, accurate)"),
            ft.dropdown.Option("large", "Large (~10GB RAM, most accurate, slowest)"),
        ],
        value="small",
        visible=False
    )
    
    whisper_transcribe_button = ft.Container(visible=False)
    whisper_progress_text = ft.Text("", size=13, color=ft.Colors.BLUE_700, visible=False)
    
    def check_ffmpeg():
        """Check if ffmpeg is installed."""
        return shutil.which('ffmpeg') is not None
    
    async def pick_wav_file(e):
        nonlocal selected_wav_path
        
        # Check if ffmpeg is available
        if not check_ffmpeg():
            result_text.value = "❌ Error: ffmpeg is not installed.\n\nTo convert WAV files, please install ffmpeg:\n• macOS: brew install ffmpeg\n• Linux: sudo apt install ffmpeg\n• Windows: Download from ffmpeg.org"
            status_text.value = "ffmpeg not found"
            status_text.color = ft.Colors.RED_400
            page.update()
            return
        
        status_text.value = "Opening file picker..."
        status_text.color = ft.Colors.BLUE_400
        page.update()
        
        files = await wav_file_picker.pick_files(
            allowed_extensions=["wav", "WAV"],
            dialog_title="Select a WAV file to convert to MP3"
        )
        
        if files:
            selected_wav_path = files[0].path
            wav_file = Path(selected_wav_path)
            
            wav_result_text.value = f"Selected: {wav_file.name}\nLocation: {wav_file.parent}"
            wav_result_text.visible = True
            status_text.value = "WAV file selected"
            status_text.color = ft.Colors.GREEN_400
            wav_convert_button.visible = True
            page.update()
        else:
            wav_result_text.visible = False
            status_text.value = "File selection cancelled"
            status_text.color = ft.Colors.ORANGE_400
            wav_convert_button.visible = False
            page.update()
    
    async def convert_wav_to_mp3(e):
        """Convert WAV file to MP3 using ffmpeg."""
        if not selected_wav_path:
            result_text.value = "Error: No WAV file selected"
            status_text.value = "Error"
            status_text.color = ft.Colors.RED_400
            page.update()
            return
        
        wav_file = Path(selected_wav_path)
        mp3_file = wav_file.with_suffix('.mp3')
        
        # Check if MP3 already exists
        if mp3_file.exists():
            result_text.value = f"⚠️  MP3 file already exists:\n{mp3_file}\n\nSkipping conversion."
            status_text.value = "MP3 already exists"
            status_text.color = ft.Colors.ORANGE_400
            page.update()
            return
        
        status_text.value = "Converting WAV to MP3..."
        status_text.color = ft.Colors.BLUE_400
        result_text.value = f"Converting {wav_file.name} to MP3...\nThis may take a few minutes for large files."
        page.update()
        
        try:
            # Run ffmpeg conversion
            # -codec:a libmp3lame: Use LAME MP3 encoder
            # -q:a 2: High quality (VBR, equivalent to ~190 kbps)
            # -ar 44100: Sample rate 44.1 kHz
            result = subprocess.run(
                [
                    'ffmpeg',
                    '-i', str(wav_file),
                    '-codec:a', 'libmp3lame',
                    '-q:a', '2',
                    '-ar', '44100',
                    str(mp3_file),
                    '-hide_banner',
                    '-loglevel', 'error'
                ],
                capture_output=True,
                text=True,
                timeout=600  # 10 minute timeout
            )
            
            if result.returncode == 0 and mp3_file.exists():
                # Success!
                wav_size = wav_file.stat().st_size / (1024 * 1024)  # MB
                mp3_size = mp3_file.stat().st_size / (1024 * 1024)  # MB
                
                result_text.value = f"✅ Conversion successful!\n\nCreated: {mp3_file.name}\nLocation: {mp3_file.parent}\n\nWAV: {wav_size:.1f} MB → MP3: {mp3_size:.1f} MB\n\nYou can now use '2. Select MP3 File' to begin transcription."
                status_text.value = "Conversion complete!"
                status_text.color = ft.Colors.GREEN_400
                wav_convert_button.visible = False
                
                # Auto-refresh progress status
                page.update()
                await refresh_status(None)
            else:
                # Error occurred
                error_msg = result.stderr if result.stderr else "Unknown error"
                result_text.value = f"❌ Error during conversion:\n\n{error_msg}"
                status_text.value = "Conversion failed"
                status_text.color = ft.Colors.RED_400
                
        except subprocess.TimeoutExpired:
            result_text.value = f"❌ Conversion timed out after 10 minutes.\n\nThe file may be too large. Try a different file or use a command-line tool."
            status_text.value = "Timeout"
            status_text.color = ft.Colors.RED_400
        except Exception as ex:
            result_text.value = f"❌ Error during conversion:\n{str(ex)}"
            status_text.value = "Error"
            status_text.color = ft.Colors.RED_400
        
        page.update()
    
    async def pick_mp3_file(e):
        nonlocal selected_mp3_path
        
        status_text.value = "Opening file picker..."
        status_text.color = ft.Colors.BLUE_400
        page.update()
        
        files = await file_picker.pick_files(
            allowed_extensions=["mp3"],
            dialog_title="Select an MP3 file to transcribe"
        )
        
        if files:
            selected_mp3_path = files[0].path
            mp3_file = Path(selected_mp3_path)
            
            result_text.value = f"Selected: {mp3_file.name}\nLocation: {mp3_file.parent}"
            status_text.value = "MP3 file selected"
            status_text.color = ft.Colors.GREEN_400
            
            # Show instructions
            show_transcription_instructions(mp3_file)
            page.update()
        else:
            result_text.value = "No file selected"
            status_text.value = "File selection cancelled"
            status_text.color = ft.Colors.ORANGE_400
            instructions_container.visible = False
            convert_button.visible = False
            page.update()
    
    async def transcribe_with_whisper(e):
        """Transcribe MP3 file using OpenAI Whisper."""
        if not selected_mp3_path:
            result_text.value = "Error: No MP3 file selected"
            status_text.value = "Error"
            status_text.color = ft.Colors.RED_400
            page.update()
            return
        
        if not WHISPER_AVAILABLE:
            result_text.value = "❌ Error: Whisper is not installed.\n\nTo use automated transcription, install Whisper:\n  pip install openai-whisper torch torchaudio"
            status_text.value = "Whisper not available"
            status_text.color = ft.Colors.RED_400
            page.update()
            return
        
        mp3_file = Path(selected_mp3_path)
        expected_docx = mp3_file.with_suffix('.docx')
        model_size = whisper_model_dropdown.value
        
        # Check if DOCX already exists
        if expected_docx.exists():
            result_text.value = f"⚠️  DOCX file already exists:\n{expected_docx}\n\nSkipping transcription."
            status_text.value = "DOCX already exists"
            status_text.color = ft.Colors.ORANGE_400
            page.update()
            return
        
        status_text.value = f"Transcribing with Whisper ({model_size} model)..."
        status_text.color = ft.Colors.BLUE_400
        whisper_progress_text.value = "Loading Whisper model... This may take a minute on first run."
        whisper_progress_text.visible = True
        whisper_transcribe_button.visible = False
        page.update()
        
        def progress_callback(message):
            """Update UI with progress messages."""
            whisper_progress_text.value = message
            page.update()
        
        try:
            # Run transcription in a thread pool to avoid blocking UI
            loop = asyncio.get_event_loop()
            await loop.run_in_executor(
                None,
                transcribe_whisper.transcribe_and_create_docx,
                str(mp3_file),
                str(expected_docx),
                model_size,
                "en",
                progress_callback
            )
            
            if expected_docx.exists():
                # Success!
                result_text.value = f"✅ Transcription successful!\n\nCreated: {expected_docx.name}\nLocation: {expected_docx.parent}\n\nYou can now convert to CSV/PDF or edit the DOCX first."
                status_text.value = "Transcription complete!"
                status_text.color = ft.Colors.GREEN_400
                whisper_progress_text.visible = False
                
                # Show the convert button
                convert_button.visible = True
                
                # Auto-refresh progress status
                page.update()
                await refresh_status(None)
            else:
                raise Exception("DOCX file was not created")
                
        except Exception as ex:
            result_text.value = f"❌ Error during transcription:\n{str(ex)}\n\nTry:\n• Using a smaller model (tiny/base)\n• Checking your audio file is valid\n• Ensuring you have enough RAM"
            status_text.value = "Transcription failed"
            status_text.color = ft.Colors.RED_400
            whisper_progress_text.visible = False
            whisper_transcribe_button.visible = True
        
        page.update()
    
    def show_transcription_instructions(mp3_file):
        """Display step-by-step transcription instructions."""
        expected_docx = mp3_file.with_suffix('.docx')
        
        # Build instructions with Whisper option first (if available)
        instruction_sections = []
        
        # Add Whisper option if available
        if WHISPER_AVAILABLE:
            whisper_section = ft.Container(
                content=ft.Column([
                    ft.Text(
                        "🤖 OPTION 1: AUTOMATED TRANSCRIPTION (RECOMMENDED)",
                        size=18,
                        weight=ft.FontWeight.BOLD,
                        color=ft.Colors.GREEN_900
                    ),
                    ft.Divider(height=10, color=ft.Colors.GREEN_200),
                    ft.Text(
                        "Use OpenAI Whisper to automatically transcribe your audio file.",
                        size=13,
                        color=ft.Colors.GREY_800
                    ),
                    ft.Container(height=5),
                    ft.Row([
                        whisper_model_dropdown,
                    ]),
                    ft.Container(height=5),
                    ft.ElevatedButton(
                        "🎙️ Transcribe with Whisper",
                        icon=ft.Icons.RECORD_VOICE_OVER,
                        on_click=transcribe_with_whisper,
                        style=ft.ButtonStyle(
                            color=ft.Colors.WHITE,
                            bgcolor=ft.Colors.GREEN_700,
                        ),
                        tooltip="Automatically transcribe audio using AI"
                    ),
                    whisper_progress_text,
                    ft.Container(height=5),
                    ft.Text(
                        "Note: First run downloads the model (~1-10GB depending on size). Processing takes 1-5 minutes per hour of audio.",
                        size=11,
                        italic=True,
                        color=ft.Colors.GREY_600
                    ),
                ], spacing=5),
                bgcolor=ft.Colors.GREEN_50,
                border=ft.Border.all(2, ft.Colors.GREEN_300),
                border_radius=8,
                padding=15
            )
            instruction_sections.append(whisper_section)
            instruction_sections.append(ft.Container(height=15))
            
            # Store button reference for visibility control
            nonlocal whisper_transcribe_button
            whisper_transcribe_button = whisper_section
            whisper_model_dropdown.visible = True
        
        # Add manual Word Online instructions
        manual_section = ft.Column([
            ft.Text(
                f"{'📝 OPTION 2: MANUAL TRANSCRIPTION' if WHISPER_AVAILABLE else '📝 TRANSCRIPTION INSTRUCTIONS'}",
                size=18,
                weight=ft.FontWeight.BOLD,
                color=ft.Colors.BLUE_900
            ),
            ft.Divider(height=10, color=ft.Colors.BLUE_200),
            
            ft.Text(
                "STEP 1: Open Microsoft Word Online",
                size=14,
                weight=ft.FontWeight.BOLD
            ),
            ft.Row([
                ft.Icon(ft.Icons.OPEN_IN_BROWSER, color=ft.Colors.BLUE_700),
                ft.TextButton(
                    "Click here to open Word Online",
                    url="https://www.office.com/launch/word",
                    style=ft.ButtonStyle(
                        color=ft.Colors.BLUE_700,
                    )
                ),
            ]),
            ft.Column([
                ft.Text("(Microsoft 365 subscription required)", size=12, italic=True),
                ft.Text("• Click 'Create blank document'", size=12, weight=ft.FontWeight.BOLD),
                ft.Text("• Copy this document name:", size=12, weight=ft.FontWeight.BOLD),
                ft.Container(
                    content=ft.Text(
                        mp3_file.stem,
                        size=13,
                        weight=ft.FontWeight.BOLD,
                        color=ft.Colors.WHITE,
                        selectable=True
                    ),
                    bgcolor=ft.Colors.BLUE_900,
                    padding=8,
                    border_radius=4
                ),
                ft.Text("• Click on 'Document X' at the top of the Word window", size=12),
                ft.Text("• Paste the name to replace it", size=12),
                ft.Text("• Press Enter to confirm", size=12),
            ], spacing=3),
            
            ft.Container(height=10),
            ft.Text(
                "STEP 2: Start Transcription",
                size=14,
                weight=ft.FontWeight.BOLD
            ),
            ft.Column([
                ft.Text("• Click the 'Home' tab (if not already selected)"),
                ft.Text("• Click 'Dictate' dropdown → Select 'Transcribe'"),
                ft.Text("• In the Transcribe pane, click 'Upload audio'"),
                ft.Text(f"• Browse to and select: {mp3_file.name}", weight=ft.FontWeight.BOLD),
                ft.Text("• Wait for transcription to complete (may take several minutes)"),
            ], spacing=5),
            
            ft.Container(height=10),
            ft.Text(
                "STEP 3: Edit & Save",
                size=14,
                weight=ft.FontWeight.BOLD
            ),
            ft.Column([
                ft.Text("• Edit speaker names if needed (e.g., replace 'Speaker 1' with actual names)"),
                ft.Text("• When complete, click 'Add to document'"),
                ft.Text("• Save the document with this EXACT name:", weight=ft.FontWeight.BOLD),
                ft.Text("  - Click the File menu in Word", style=ft.TextStyle(italic=True)),
                ft.Text("  - Select 'Create a Copy'", style=ft.TextStyle(italic=True)),
                ft.Text("  - Select 'Download a Copy'", style=ft.TextStyle(italic=True)),
                ft.Text("  - Click 'Download a Copy' to confirm", style=ft.TextStyle(italic=True)),
                ft.Text("  - The file will be saved to your Downloads folder", style=ft.TextStyle(italic=True)),
                ft.Container(
                    content=ft.Text(
                        expected_docx.name,
                        size=13,
                        weight=ft.FontWeight.BOLD,
                        color=ft.Colors.WHITE
                    ),
                    bgcolor=ft.Colors.BLUE_900,
                    padding=8,
                    border_radius=4
                ),
                ft.Text(
                    f"• Save it in the SAME folder as the MP3:",
                    weight=ft.FontWeight.BOLD
                ),
                ft.Container(
                    content=ft.Text(
                        str(mp3_file.parent),
                        size=12,
                        selectable=True
                    ),
                    bgcolor=ft.Colors.GREY_100,
                    padding=8,
                    border_radius=4
                ),
            ], spacing=5),
            
            ft.Container(height=10),
            ft.Text(
                "STEP 4: Convert to CSV and PDF",
                size=14,
                weight=ft.FontWeight.BOLD
            ),
            ft.Text("Once you've saved the DOCX file, click the button below to create both CSV and PDF versions."),
        ], spacing=8)
        
        instruction_sections.append(manual_section)
        
        # Combine all sections
        instructions_content = ft.Column(instruction_sections, spacing=0)
        
        instructions_container.content = instructions_content
        instructions_container.visible = True
        convert_button.visible = True
    
    async def convert_docx_to_csv(e):
        """Run parse_transcript.py to convert DOCX to CSV."""
        if not selected_mp3_path:
            result_text.value = "Error: No MP3 file selected"
            status_text.value = "Error"
            status_text.color = ft.Colors.RED_400
            page.update()
            return
        
        mp3_file = Path(selected_mp3_path)
        expected_docx = mp3_file.with_suffix('.docx')
        expected_csv = mp3_file.with_suffix('.csv')
        expected_pdf = mp3_file.with_suffix('.pdf')
        
        # Check if DOCX exists
        if not expected_docx.exists():
            result_text.value = f"❌ Error: DOCX file not found!\n\nExpected file:\n{expected_docx}\n\nPlease complete the transcription steps above and save the file."
            status_text.value = "DOCX file not found"
            status_text.color = ft.Colors.RED_400
            page.update()
            return
        
        status_text.value = "Converting DOCX to CSV and PDF..."
        status_text.color = ft.Colors.BLUE_400
        result_text.value = "Processing transcript, please wait..."
        page.update()
        
        try:
            # Get the path to parse_transcript.py in the same directory
            script_dir = Path(__file__).parent
            parse_script = script_dir / "parse_transcript.py"
            
            if not parse_script.exists():
                result_text.value = f"❌ Error: parse_transcript.py not found at:\n{parse_script}"
                status_text.value = "Script not found"
                status_text.color = ft.Colors.RED_400
                page.update()
                return
            
            # Run parse_transcript.py
            result = subprocess.run(
                [sys.executable, str(parse_script), str(expected_docx), str(expected_csv)],
                capture_output=True,
                text=True
            )
            
            if result.returncode == 0:
                # Success!
                result_text.value = f"✅ Success!\n\nFiles created:\n• CSV: {expected_csv}\n• PDF: {expected_pdf}\n\n{result.stdout}"
                status_text.value = "Conversion complete!"
                status_text.color = ft.Colors.GREEN_400
                
                # Auto-refresh progress status
                page.update()
                await refresh_status(None)
            else:
                # Error occurred
                result_text.value = f"❌ Error during conversion:\n\n{result.stderr}\n\n{result.stdout}"
                status_text.value = "Conversion failed"
                status_text.color = ft.Colors.RED_400
                
        except Exception as ex:
            result_text.value = f"❌ Error running conversion:\n{str(ex)}"
            status_text.value = "Error"
            status_text.color = ft.Colors.RED_400
        
        page.update()
    
    async def refresh_status(e):
        """Refresh the PROGRESS_STATUS.md file."""
        status_text.value = "Refreshing progress status..."
        status_text.color = ft.Colors.BLUE_400
        result_text.value = "Scanning Reunion-2025-Oral-Histories directory..."
        page.update()
        
        success, message = update_progress_status()
        
        if success:
            result_text.value = f"✅ Progress Status Updated!\n\n{message}\n\nPROGRESS_STATUS.md has been updated with current interview status."
            status_text.value = "Status refreshed"
            status_text.color = ft.Colors.GREEN_400
        else:
            result_text.value = f"❌ Error updating status:\n\n{message}"
            status_text.value = "Refresh failed"
            status_text.color = ft.Colors.RED_400
        
        page.update()
    
    # Create FilePickers
    file_picker = ft.FilePicker()
    wav_file_picker = ft.FilePicker()
    page.services.append(file_picker)
    page.services.append(wav_file_picker)
    
    # Configure convert buttons
    wav_convert_button.content = ft.Button(
        "Convert WAV to MP3",
        icon=ft.Icons.SYNC,
        on_click=convert_wav_to_mp3,
        style=ft.ButtonStyle(
            color=ft.Colors.WHITE,
            bgcolor=ft.Colors.PURPLE_700,
        )
    )
    
    convert_button.content = ft.Button(
        "Convert DOCX to CSV & PDF",
        icon=ft.Icons.TRANSFORM,
        on_click=convert_docx_to_csv,
        style=ft.ButtonStyle(
            color=ft.Colors.WHITE,
            bgcolor=ft.Colors.GREEN_700,
        )
    )
    
    # Build UI
    page.add(
        ft.Container(
            content=ft.Column(
                [
                    # Header
                    ft.Text(
                        "Oral History Workflow",
                        size=28,
                        weight=ft.FontWeight.BOLD,
                        color=ft.Colors.BLUE_900
                    ),
                    ft.Text(
                        "WAV/MP3 → Transcription → CSV/PDF Pipeline",
                        size=16,
                        color=ft.Colors.GREY_700
                    ),
                    ft.Divider(height=20, color=ft.Colors.BLUE_200),
                    
                    # Optional: WAV to MP3 converter
                    ft.Container(
                        content=ft.Column([
                            ft.Text(
                                "Optional: Convert WAV to MP3",
                                size=14,
                                weight=ft.FontWeight.BOLD,
                                color=ft.Colors.GREY_700
                            ),
                            ft.Button(
                                "Select WAV File",
                                icon=ft.Icons.AUDIO_FILE,
                                on_click=pick_wav_file,
                                style=ft.ButtonStyle(
                                    color=ft.Colors.WHITE,
                                    bgcolor=ft.Colors.PURPLE_700,
                                )
                            ),
                            wav_result_text,
                            wav_convert_button,
                        ], spacing=8),
                        bgcolor=ft.Colors.PURPLE_50,
                        border=ft.Border.all(2, ft.Colors.PURPLE_200),
                        border_radius=8,
                        padding=15
                    ),
                    
                    ft.Container(height=10),
                    
                    # File picker button
                    ft.Container(
                        content=ft.Button(
                            "2. Select MP3 File",
                            icon=ft.Icons.AUDIO_FILE,
                            on_click=pick_mp3_file,
                            style=ft.ButtonStyle(
                                color=ft.Colors.WHITE,
                                bgcolor=ft.Colors.BLUE_700,
                            )
                        ),
                        padding=ft.Padding(left=0, top=0, right=0, bottom=10)
                    ),
                    
                    # Status
                    status_text,
                    ft.Container(height=5),
                    
                    # Result display
                    ft.Container(
                        content=result_text,
                        bgcolor=ft.Colors.GREY_100,
                        border=ft.Border.all(1, ft.Colors.GREY_300),
                        border_radius=8,
                        padding=15,
                    ),
                    
                    ft.Container(height=15),
                    
                    # Instructions (hidden initially)
                    instructions_container,
                    
                    ft.Container(height=10),
                    
                    # Convert button (hidden initially)
                    convert_button,
                    
                    ft.Container(height=10),
                    
                    # Refresh Status button
                    ft.Container(
                        content=ft.Button(
                            "🔄 Refresh Progress Status",
                            icon=ft.Icons.REFRESH,
                            on_click=refresh_status,
                            style=ft.ButtonStyle(
                                color=ft.Colors.WHITE,
                                bgcolor=ft.Colors.ORANGE_700,
                            ),
                            tooltip="Scan interviews and update PROGRESS_STATUS.md"
                        ),
                        padding=ft.Padding(left=0, top=10, right=0, bottom=0)
                    ),
                ],
                scroll=ft.ScrollMode.AUTO,
                spacing=5,
                expand=True
            ),
            expand=True
        )
    )
    
    # Auto-refresh status on startup
    async def on_startup():
        await refresh_status(None)
    
    page.on_route_change = lambda e: None  # Placeholder
    page.run_task(on_startup)


if __name__ == "__main__":
    ft.run(main)
